### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by resekai-id** [Setiawan007/Temporary-Gmail#1]
E:\BOT\Temporary-Gmail>python main.py
Traceback (most recent call last):
  File "E:\BOT\Temporary-Gmail\main.py", line 18, in <module>
    mailbox.Login()
  File "E:\BOT\Temporary-Gmail\Helpers\Email.py", line 17, in Login
    ).login(config.get("Email"), config.get("Password"))
  File "C:\Users\arh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\imap_tools\mailbox.py", line 65, in login
    check_command_status(login_result, MailboxLoginError)
  File "C:\Users\arh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\imap_tools\utils.py", line 46, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']

how to fix?

**Comment by develop-pex** [comment]
you can on 2-Step Verification and then create app password
